version: '3.9'

services:
  bot_app:
    build: 
      context: .
    container_name: bot_application
    # entrypoint: ['/app/start.sh']
    command: sh -c "python -m src.bot.bot && python -m src.bot.broker.bot_consumer && python -m src.bot.broker.nn_consumer && python -m src.bot.broker.parser_consumer && python -m src.bot.broker.preprocessing_consumer"
    volumes:
      - ./models/cc.ru.300.bin:/app/models/cc.ru.300.bin:ro
      - ./models/cc.ru.300.bin.gz:/app/models/cc.ru.300.bin.gz
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3.10.7-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /