version: '3.9'

services:
  bot_app:
    build: 
      context: .
    container_name: bot_application
    entrypoint: ['/app/start.sh']
    volumes:
      - ./src/bot/broker/cc.ru.300.bin:/app/src/bot/broker/cc.ru.300.bin
      - ./src/bot/broker/cc.ru.300.bin.gz:/app/src/bot/broker/cc.ru.300.bin.gz

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest